# Assignment 22

## Question 1

What are the benefits of the built-in array package, if any?

## Answer to the Question 1

Python's built-in array package makes it easy to store and handle fundamental data types including integers, characters, and floating point numbers. It enables for the efficient shrinking and expanding of arrays, as well as the ability to work with array elements via indexing and slicing. The array package also includes functions for searching, sorting, and reversing arrays. Finally, the array package saves memory and can be used instead of regular lists and tuples when space is limited.

## Question 2

What are some of the array package's limitations?

## Answer to the Question 2

The array library in Python has limited ability in working with sophisticated data types like objects and dictionaries. Furthermore, because the array package does not handle multidimensional arrays, it cannot store matrices or higher-dimensional data. Because the array package does not permit dynamic resizing, the array's size must be given at the time of creation. Finally, the array package lacks any built-in sorting or searching algorithms, and so they have to be developed manually.

## Question 3

Describe the main differences between the array and numpy packages.

## Answer to the Question 3

The array and NumPy packages differ as the array module can only store basic data data types such as integers, characters, and floating point numbers, while NumPy can store more complicated data types such as objects and dictionaries. Furthermore, whereas NumPy supports multidimensional arrays, the array package does not. Finally, unlike NumPy, the array package does not support dynamic scaling. NumPy also contains array searching, sorting, and reversing functions, as well as matrix operations such as determining the inverse of a matrix.

## Question 4

Explain the distinctions between the empty, ones, and zeros functions.

## Answer to the Question 4

The main difference between the functions `empty()`, `ones()`, and `zeros()` is that `empty()` does not set the array values to any specific value, whereas `ones()` assigns values of 1 to all the members in the array and `zeros()` assigns values of 0 to all the elements in the array. Furthermore, while `empty()` is faster than both `ones()` and `zeros()`, it requires the user to manually assign values to the array's entries. `ones()` and `zeros()`, on the other hand, are both slower than `empty()` but provide the convenience of automatically updating the values of array components.

## Question 5

In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

## Answer to the Question 5

The callable argument in NumPy's fromfunction function is a function or callable object that is utilized to generate the values for the new array.

The form and callable arguments are required by the fromfunction function. The shape argument is a tuple that describes the shape of the newly created array. The callable argument is a function or callable object that takes the array indices as input and returns the value to be placed in the array.

The callable function is called with a tuple of indices corresponding to the position of each array element. For example, f or a two-dimensional array, if the shape argument is (3, 3), the callable function will be called with tuples (0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), and (2, 2).

The values returned by the callable function are utilized to populate the relevant element in the new array. The newly created array is then returned by the fromfunction function.

Below is an example code illustrating the use of `fromfunction`

In [1]:
import numpy as np

def my_func(x, y):
    return x + y

arr = np.fromfunction(my_func, (3, 3))

print(arr)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


## Question 6

What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

## Answer to the Question 6

When a NumPy array is added to a single-value operand (a scalar such as an int or a floating-point value) using addition, the scalar is added to each element of the array. For example, if A is a one-dimensional array, A + n creates a new one-dimensional array by increasing each element of A by n. Similarly, if A is a two-dimensional array, A + n creates a new two-dimensional array by increasing each element of A by n.

## Question 7

Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

## Answer to the Question 7

Yes, in Python, array-to-scalar operations can use combined operation-assign operators like `+=` or `*=`. T he value of the array element will be increased or reduced by the value of the scalar. For example, if `array[0]` is 5 and the combination operator is `+= 3`, the value of `array[0]` will be 8 as a result of the operation.

## Question 8

Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

## Answer to the Question 8

Fixed-length strings do not exist in NumPy arrays. If you try to assign a longer string to one of these arrays, we will get a ValueError since the array cannot store strings of varying lengths. With the object data type, it is feasible to store strings of varying lengths in a two-dimensional array.

## Question 9

What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

## Answer to the Question 9

When you combine two NumPy arrays using an operation like addition `+` or multiplication `*`, the arrays must be of the same shape for the operation to work. A `ValueError` will be thrown if the arrays have different shapes. Furthermore, both arrays must have the elements of the same data type, or a `TypeError` will be thrown.

## Question 10

What is the best way to use a Boolean array to mask another array?

## Answer to the Question 10

In NumPy, one of the most common and effective uses of a Boolean array is as a mask for another array. This entails picking elements from an array depending on a Boolean condition defined in a second Boolean array. Below is an example code:

In [3]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])

# Create a Boolean mask to select even numbers
mask = arr % 2 == 0

# Use the mask to select only even numbers from the array
result = arr[mask]

# Print the result
print(result)

[10 20 30 40 50]


## Question 11

What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

## Answer to the Question 11

Following are the three ways which we can use to get the standard deviation.

1. **Using NumPy:** The standard deviation function in NumPy provides the quickest way to calculate the standard deviation of a large collection of data. The syntax is `np.std(data)`, where data is an array of data points.

2. **Using the statistics module:** Python's statistics module includes an extremely fast `stdev()` function. For data array, we can use `statistics.stdev(data)` to calculate this.

3. **Using a for loop:** This is the most time-consuming method because it entails iterating through the data points, summing them, determining the mean, and finally calculating the standard deviation.

## Question 12

What is the dimensionality of a Boolean mask-generated array?

## Answer to the Question 12

The dimensionality of a Boolean mask generateed array is determined by the shape of the input array and the shape of the Boolean mask.

When a Boolean mask is applied to an array, the resulting array has the same dimensions as the original array. However, because only components that match the criterion given in the mask are maintained, the size of the resulting array along the masked axis may be reduced.