# Programming Assignment 8

## Question 1

Write a Python Program to Add Two Matrices?

## Answer to the Question 1

In [1]:
def add_matrices(x, y):
    # Assumption is that x and y have same dimension
    rows = len(x)
    cols = len(x[0])
    import numpy as np
    result = np.zeros((rows, cols))
    for i in range(rows):
        for j in range(cols):
            result[i][j] = x[i][j] + y[i][j]
    return result

In [2]:
matrix_A = [[1,2,3,4],[10,20,30,40],[3,5,1,3]]
matrix_B = [[1,3,4,5], [7,8,9,10], [3,3,3,3]]
add_matrices(matrix_A, matrix_B)

array([[ 2.,  5.,  7.,  9.],
       [17., 28., 39., 50.],
       [ 6.,  8.,  4.,  6.]])

## Question 2

Write a Python Program to Multiply Two Matrices?

## Answer to the Question 2

In [3]:
def multiply_matrices(x, y):
    # Assumption is that x and y have same dimension
    rows = len(x)
    cols = len(x[0])
    import numpy as np
    result = np.zeros((rows, cols))
    for i in range(rows):
        for j in range(cols):
            result[i][j] = x[i][j] * y[i][j]
    return result

In [4]:
multiply_matrices(matrix_A, matrix_B)

array([[  1.,   6.,  12.,  20.],
       [ 70., 160., 270., 400.],
       [  9.,  15.,   3.,   9.]])

## Question 3

Write a Python Program to Transpose a Matrix?

## Answer to the Question 3

In [11]:
def transpose_matrices(x):
    rows = len(x)
    cols = len(x[0])
    import numpy as np
    result = np.zeros((cols, rows))
    for i in range(cols):
        for j in range(rows):
            result[i][j] = x[j][i]
    print(result)

In [13]:
print(matrix_A)

[[1, 2, 3, 4], [10, 20, 30, 40], [3, 5, 1, 3]]


In [12]:
transpose_matrices(matrix_A)

[[ 1. 10.  3.]
 [ 2. 20.  5.]
 [ 3. 30.  1.]
 [ 4. 40.  3.]]


## Question 4

Write a Python Program to Sort Words in Alphabetic Order?

## Answer to the Question 4

In [16]:
def sort_words(words):
    words.sort()
    return words

In [17]:
sort_words(["banana", "pineapple", "mango", "strawberry", "orange"])

['banana', 'mango', 'orange', 'pineapple', 'strawberry']

## Question 5

Write a Python Program to Remove Punctuation From a String?

## Answer to the Question 5

In [18]:
def remove_punctuation(string):
    punctuations = '''!()-[]{};:'"\,<>.?@#$%^&*_~'''
    without_punc = ""
    for char in string:
        if char not in punctuations:
            without_punc += char
    return without_punc

In [19]:
remove_punctuation("nfvafdksjvn!@#$%%^mvsdafmv:")

'nfvafdksjvnmvsdafmv'

In [20]:
remove_punctuation("@#Hi, I am Klingerslokas ^^&&& Got it")

'Hi I am Klingerslokas  Got it'